-- Migration: init
-- Generated by assistant to create tables matching prisma/schema.prisma

-- Note: Prisma uses client-generated cuid() by default for String @id with cuid().
-- This migration creates tables and constraints to match Prisma schema.prisma.

CREATE TABLE IF NOT EXISTS "User" (
  "id" text NOT NULL PRIMARY KEY,
  "firstName" text NOT NULL,
  "lastName" text NOT NULL,
  "phone" text NOT NULL,
  "passwordHash" text NOT NULL,
  "baseBalance" numeric(15,2) NOT NULL DEFAULT 0,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "User_phone_key" ON "User" ("phone");
CREATE INDEX IF NOT EXISTS "User_phone_idx" ON "User" ("phone");
CREATE INDEX IF NOT EXISTS "User_createdAt_idx" ON "User" ("createdAt");

CREATE TABLE IF NOT EXISTS "Investment" (
  "id" text NOT NULL PRIMARY KEY,
  "userId" text NOT NULL,
  "planId" text NOT NULL,
  "planName" text NOT NULL,
  "amount" numeric(15,2) NOT NULL,
  "profitRate" numeric(5,4) NOT NULL,
  "returnDays" integer NOT NULL DEFAULT 180,
  "startTimestamp" bigint NOT NULL,
  "endTimestamp" bigint NOT NULL,
  "accumulatedEarnings" numeric(15,2) NOT NULL DEFAULT 0,
  "lastCalculatedTimestamp" bigint NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "Investment_user_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "Investment_userId_idx" ON "Investment" ("userId");
CREATE INDEX IF NOT EXISTS "Investment_status_idx" ON "Investment" ("status");
CREATE INDEX IF NOT EXISTS "Investment_startTimestamp_idx" ON "Investment" ("startTimestamp");
CREATE INDEX IF NOT EXISTS "Investment_endTimestamp_idx" ON "Investment" ("endTimestamp");

CREATE TABLE IF NOT EXISTS "Withdrawal" (
  "id" text NOT NULL PRIMARY KEY,
  "userId" text NOT NULL,
  "amount" numeric(15,2) NOT NULL,
  "method" text NOT NULL DEFAULT 'telebirr',
  "telebirrPhone" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "requestedAt" bigint NOT NULL,
  "pendingUntil" bigint NOT NULL,
  "completedAt" bigint,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "Withdrawal_user_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "Withdrawal_userId_idx" ON "Withdrawal" ("userId");
CREATE INDEX IF NOT EXISTS "Withdrawal_status_idx" ON "Withdrawal" ("status");
CREATE INDEX IF NOT EXISTS "Withdrawal_requestedAt_idx" ON "Withdrawal" ("requestedAt");

CREATE TABLE IF NOT EXISTS "Deposit" (
  "id" text NOT NULL PRIMARY KEY,
  "userId" text NOT NULL,
  "amount" numeric(15,2) NOT NULL,
  "method" text NOT NULL DEFAULT 'telebirr',
  "status" text NOT NULL DEFAULT 'pending',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "Deposit_user_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "Deposit_userId_idx" ON "Deposit" ("userId");
CREATE INDEX IF NOT EXISTS "Deposit_status_idx" ON "Deposit" ("status");
CREATE INDEX IF NOT EXISTS "Deposit_createdAt_idx" ON "Deposit" ("createdAt");

CREATE TABLE IF NOT EXISTS "Session" (
  "id" text NOT NULL PRIMARY KEY,
  "userId" text NOT NULL,
  "token" text NOT NULL,
  "expiresAt" timestamptz NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "Session_user_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "Session_token_key" ON "Session" ("token");
CREATE INDEX IF NOT EXISTS "Session_userId_idx" ON "Session" ("userId");
CREATE INDEX IF NOT EXISTS "Session_token_idx" ON "Session" ("token");
CREATE INDEX IF NOT EXISTS "Session_expiresAt_idx" ON "Session" ("expiresAt");
